#!/usr/bin/env python3
"""Generate each host's files for host setup v1 (E05; node/docs/architecture/host-setup-v1.md).

  host_files.py --release DIR --chain DIR --hosts DIR --plan PIN_PLAN.json --keys DIR
                [--values E05_VALUES.json] [--setup SETUP_VALUES.json] --out DIR

Inputs, all public:
  --release  the release's RELEASE_MANIFEST.json and BUILD_RECORD.json
  --chain    application-config.json, native-genesis.json, genesis.json (the
             engine genesis), root-policy.json and root-signatures.json
  --hosts    dytallix-host-config's output (hosts/LABEL/{config.toml,
             pqc_transport.json,binding.json} and PIN_PLAN_BINDINGS.json)
  --plan     the pin plan
  --keys     LABEL.keys.json for each host, from the offline key step: the
             host's public keys and the SHA-256 of each secret file; and, for
             the endpoint, LABEL.channel-pin.json
  --values   launch/E05_VALUES.json; --setup launch/hosts/SETUP_VALUES.json

For each host, OUT/LABEL/ holds every file it installs, under its absolute
path (etc/dytallix/RELEASE/..., var/lib/dytallix/node/config/..., the unit,
the AppArmor profiles, the firewall table and the journal setting), and
INSTALL_MANIFEST.json:
each file's path, SHA-256, owner and mode, the directories, the release
binaries and the secret files the sealed keys must provide. The execution
policy comes from native-execution-policy's production_roles.py, and the
supervisor's service configuration pins the SHA-256 of every file it reads.
Nothing here is secret: the secret files are only named and digested.
"""
import argparse
import base64
import hashlib
import json
from pathlib import Path, PurePosixPath
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / 'native-execution-policy'))
import production_roles  # noqa: E402
import render  # noqa: E402

SCHEMA = 'dytallix.host-install.v1'
KEYS_SCHEMA = 'dytallix.host-keys.v1'
SETUP_SCHEMA = 'dytallix.host-setup-values.v1'
MiB = 1 << 20

# The approved layout (P01, 6 October 2026; host-setup-v1.md).
USER, UID, GID, UNIT = 'dytallix', 41001, 41001, 'dytallix-node'
HOME = '/var/lib/dytallix/node'
LOCK = '/var/lib/dytallix/lock'
METRICS = '/var/lib/dytallix/metrics'
SNAPSHOTS = '/var/lib/dytallix/snapshots'
LIGHT_BLOCKS = '/var/lib/dytallix/light-blocks'
SCRATCH = '/var/lib/dytallix/scratch'
# The adapter's loopback listener on the endpoint, behind its client channel
# and status page; reachable only on the host.
ADAPTER_LISTEN = '127.0.0.1:26671'
# The journal on disk for 90 days, the operations objectives' log retention.
JOURNALD = '/etc/systemd/journald.conf.d/dytallix.conf'
JOURNALD_CONF = (b'# Dytallix node (host setup v1). Generated by host_files.py; do not edit.\n'
                 b'[Journal]\nStorage=persistent\nMaxRetentionSec=90d\n')

# Bounds of the files the supervisor pins, from the node's own limits.
PIN_BOUNDS = {
    'consensus_config': 8 * MiB,      # consensus_settlement MAX_CONFIG_BYTES
    'application_genesis': 8 * MiB,   # consensus_settlement MAX_GENESIS_BYTES
    'small_config': 65536,            # root, emergency verifier, candidate (native-supervisor)
    'admission': 65536,
    'root_policy': 65536,
    'root_signatures': 512 * 1024,    # five 29,792-byte signatures, hex
    'config.toml': 65536,
    'genesis.json': 9 * MiB,          # enginepqc MaxGenesisBytes
    'pqc_peer_seed.bin': 4096,
    'pqc_transport.json': 512 * 1024,
    'priv_validator_key.json': 65536,
    'binding': 4096,                  # native-supervisor MAX_BINDING_BYTES
    'channel_pin': 8192,              # client-channel MAX_PIN_BYTES
}
ROLES = ('validator', 'sentry', 'endpoint')


class Invalid(ValueError):
    pass


def require(ok, message):
    if not ok:
        raise Invalid(message)


def sha256(raw):
    return hashlib.sha256(raw).hexdigest()


def compact(value):
    return json.dumps(value, separators=(',', ':')).encode()


def pretty(value):
    return (json.dumps(value, indent=2) + '\n').encode()


def read_json(path):
    try:
        return json.loads(Path(path).read_bytes())
    except (OSError, ValueError) as error:
        raise Invalid(f'{path}: {error}') from error


def e05_approved(values):
    """Approved E05 values by path."""
    return {row['path']: row['approved'] for row in values['values']
            if row.get('status') == 'APPROVED' and row.get('path')}


def service_value(approved, name):
    key = 'service.' + name
    require(key in approved, f'E05 value {key} is not approved')
    return approved[key]


def unit_file(properties, exec_start):
    """The systemd unit: the rendered properties under [Service]."""
    def value(v):
        if isinstance(v, bool):
            return 'yes' if v else 'no'
        if isinstance(v, list):
            return ' '.join(str(x) for x in v)
        return str(v)
    service = [f'{name}={value(v)}' for name, v in sorted(properties.items())]
    lines = [
        '# Dytallix node (host setup v1). Generated by host_files.py; do not edit.',
        '[Unit]',
        'Description=Dytallix node supervisor',
        'Wants=network-online.target time-sync.target',
        'After=network-online.target time-sync.target apparmor.service nftables.service',
        'Requires=apparmor.service nftables.service',
        '',
        '[Service]',
        'Type=simple',
        f'ExecStart={exec_start}',
        # An operator restarts the node after a refusal or a halt (runbooks).
        'Restart=no',
        # Above the supervisor's 30 s stop and 10 s kill budget.
        'TimeoutStopSec=60',
        'KillSignal=SIGTERM',
        'StandardOutput=journal',
        'StandardError=journal',
        *service,
        '',
        '[Install]',
        'WantedBy=multi-user.target',
        '',
    ]
    return '\n'.join(lines).encode()


def host(label, plan_host, *, release, chain, hosts, keys, approved, setup):
    """Every file of one host, by absolute path, and its install manifest."""
    role = plan_host['role']
    require(role in ROLES, f'{label}: unknown role {role}')
    require(plan_host['home'] == HOME, f'{label}: the plan home must be {HOME} (host-setup-v1)')
    manifest_raw = release['manifest']
    catalog = json.loads(manifest_raw)
    release_id = hashlib.sha512(manifest_raw).hexdigest()[:16]
    bin_dir = f'/opt/dytallix/{release_id}/bin'
    etc = f'/etc/dytallix/{release_id}'
    members = {m['id']: m for m in catalog['members']}
    roles = {r['role']: r['member_id'] for r in catalog['roles']}
    record_members = release['record']['members']
    for member_id, member in members.items():
        recorded = record_members.get(member_id)
        require(recorded is not None and recorded['sha256'] == member['sha256'] and recorded['bytes'] == member['bytes'],
                f'catalog member {member_id} is not the build record\'s binary')
    files = {}

    def add(path, raw):
        require(path not in files, f'{path} written twice')
        files[path] = raw

    # Engine files from dytallix-host-config, installed under the home.
    host_dir = hosts['dir'] / 'hosts' / label
    config_toml = (host_dir / 'config.toml').read_bytes()
    transport = (host_dir / 'pqc_transport.json').read_bytes()
    binding = (host_dir / 'binding.json').read_bytes()
    engine_genesis = chain['genesis.json']
    add(f'{HOME}/config/config.toml', config_toml)
    add(f'{HOME}/config/pqc_transport.json', transport)
    add(f'{HOME}/config/genesis.json', engine_genesis)
    planned = next((h for h in hosts['bindings']['hosts'] if h['label'] == label), None)
    require(planned is not None, f'{label} is not in PIN_PLAN_BINDINGS.json')
    firewall = planned['firewall']
    require(firewall['transport_sha256'] == sha256(transport), f'{label}: the bindings name another transport file')

    # Keys made offline: public parts here, secrets only digested.
    key = keys[label]
    require(key['schema'] == KEYS_SCHEMA and key['label'] == label and key['role'] == role,
            f'{label}: the key summary is for another host')
    require(key['peer_public_key_base64'] == plan_host['peer_public_key_base64']
            and key['validator_public_key_base64'] == plan_host['validator_public_key_base64'],
            f'{label}: the key summary differs from the plan')
    validator_public = base64.b64decode(key['validator_public_key_base64'], validate=True)
    require(len(validator_public) == 1952, f'{label}: the validator key is not ML-DSA-65')
    secrets = key['secret_files']
    expected = {'config/pqc_peer_seed.bin', 'config/priv_validator_key.json', 'data/priv_validator_state.json'}
    if role == 'endpoint':
        expected.add('config/client_channel_seed.bin')
    require(set(secrets) == expected, f'{label}: the sealed keys must be exactly {sorted(expected)}')

    # The catalog mapping: each member at its installed path.
    mapping = {'schema': 1, 'members': [{'id': m, 'path': f'{bin_dir}/{m}'} for m in sorted(members)]}
    mapping_raw = compact(mapping)

    # Everything the unit reads outside its writable roots.
    etc_files = {
        'release-manifest.json': manifest_raw,
        'mapping.json': mapping_raw,
        'application-config.json': chain['application-config.json'],
        'native-genesis.json': chain['native-genesis.json'],
        'root-policy.json': chain['root-policy.json'],
        'root-signatures.json': chain['root-signatures.json'],
        'binding.json': binding,
    }
    if role == 'endpoint':
        etc_files['channel-pin.json'] = keys['pins'][label]
    readonly = sorted([f'{etc}/{name}' for name in etc_files] +
                      [f'{etc}/{name}' for name in ('admission.json', 'root-config.json',
                                                     'emergency-verifier.json', 'candidate.json', 'service.json')])
    writable = [HOME, LOCK, METRICS, SCRATCH] + ([SNAPSHOTS] if role == 'sentry' else [])
    request = {
        'schema': 1, 'policy_version': render.VERSION, 'catalog_sha512': hashlib.sha512(manifest_raw).hexdigest(),
        'service_uids': [UID], 'writable_roots': sorted(writable), 'readonly_files': readonly,
        'code_aliases': [], 'devices': ['/dev/null', '/dev/urandom'],
        'network': {'mode': 'routed', 'namespace_path': None,
                    'sockets': [{'family': 'unix', 'type': 'stream'}, {'family': 'inet', 'type': 'stream'}],
                    'firewall': firewall, 'launch_channel': render.LAUNCH_CHANNEL},
        'resources': setup['unit'],
    }
    identities = [{'unit': UNIT, 'uid': UID, 'gid': GID}]
    try:
        policy = production_roles.generate(manifest_raw, mapping, request, identities,
                                           candidate_only=True, transport=transport)
    except render.Invalid as error:
        raise Invalid(f'{label}: execution policy: {error}') from error
    admission_raw = policy[f'admission-{UNIT}.json']
    admission = json.loads(admission_raw)
    unit_properties = json.loads(policy['unit-properties.json'])['units'][0]
    require(unit_properties['unit'] == UNIT, 'unexpected unit')

    # The root helper: the one binary both verifier roles name.
    helper_id = roles['genesis_bootstrap_verifier']
    require(roles['control_verifier'] == helper_id, 'both verifier roles name the root helper')
    helper = members[helper_id]
    helper_path = f'{bin_dir}/{helper_id}'
    root_setup = setup['root']
    # The node refuses an observed file bound above the helper bound
    # (ObservedHelperPolicy), and both verifier configurations share it.
    observation = setup['root_helper_observation']
    for name, bound in (('root', root_setup['max_helper_bytes']),
                        ('emergency verifier', approved['emergency verifier config max_helper_bytes'])):
        require(observation['max_file_bytes'] <= bound,
                f'the root helper observation\'s max_file_bytes exceeds the {name} max_helper_bytes')
    helper_execution = {
        'profile': 'linux-immutable-observed-helper-v1',
        'helper_bytes': helper['bytes'], 'helper_sha512': helper['sha512'],
        'owner_security': {name: admission[name] for name in
                           ('supervisor_label', 'application_owner_label', 'workload_label', 'helper_label', 'uid', 'gid')},
        **setup['root_helper_observation'],
    }
    root_config = {
        'profile': 'SLH-DSA-SHAKE-256s',
        'helper_path': helper_path,
        'helper_execution': helper_execution,
        'helper_sha256': helper['sha256'],
        'max_helper_bytes': root_setup['max_helper_bytes'],
        'max_request_bytes': root_setup['max_request_bytes'],
        'timeout_ms': root_setup['timeout_ms'],
        'policy_path': f'{etc}/root-policy.json',
        'signatures_path': f'{etc}/root-signatures.json',
        'engine_genesis_path': f'{HOME}/config/genesis.json',
        'max_engine_genesis_bytes': root_setup['max_engine_genesis_bytes'],
        'engine_genesis_sha512': hashlib.sha512(engine_genesis).hexdigest(),
        'release_manifest_path': f'{etc}/release-manifest.json',
        'max_release_manifest_bytes': root_setup['max_release_manifest_bytes'],
        'release_manifest_sha512': hashlib.sha512(manifest_raw).hexdigest(),
    }
    emergency_verifier = {
        'helper_path': helper_path,
        'helper_scratch_path': SCRATCH,
        'helper_execution': helper_execution,
        'helper_sha256': helper['sha256'],
        'max_helper_bytes': approved['emergency verifier config max_helper_bytes'],
        'max_request_bytes': approved['emergency verifier config max_request_bytes'],
        'timeout_ms': setup['emergency_verifier_timeout_ms'],
    }
    require(approved.get('emergency verifier config timeout_ms', setup['emergency_verifier_timeout_ms'])
            == setup['emergency_verifier_timeout_ms'], 'the setup values and E05 name different emergency verifier timeouts')
    candidate = {
        'config_schema': 2,
        'manifest_path': f'{etc}/release-manifest.json',
        'mapping_path': f'{etc}/mapping.json',
        'bounds': setup['catalog_bounds'],
        'observation': setup['observation_bounds'],
        'allowed_owner_uids': sorted(setup['code_owner_uids']),
    }
    small = {'admission.json': admission_raw, 'root-config.json': pretty(root_config),
             'emergency-verifier.json': pretty(emergency_verifier), 'candidate.json': pretty(candidate)}
    for name, raw in small.items():
        require(len(raw) <= PIN_BOUNDS['small_config'], f'{name} exceeds the supervisor\'s 64 KiB bound')
    etc_files.update(small)

    def pin(path, raw, bound):
        require(len(raw) <= bound, f'{path} exceeds its {bound}-byte bound')
        return {'path': path, 'sha256': sha256(raw), 'max_bytes': bound}

    engine_inputs = [
        pin(f'{HOME}/config/config.toml', config_toml, PIN_BOUNDS['config.toml']),
        pin(f'{HOME}/config/genesis.json', engine_genesis, PIN_BOUNDS['genesis.json']),
        {'path': f'{HOME}/config/pqc_peer_seed.bin', 'sha256': secrets['config/pqc_peer_seed.bin'],
         'max_bytes': PIN_BOUNDS['pqc_peer_seed.bin']},
        pin(f'{HOME}/config/pqc_transport.json', transport, PIN_BOUNDS['pqc_transport.json']),
        {'path': f'{HOME}/config/priv_validator_key.json', 'sha256': secrets['config/priv_validator_key.json'],
         'max_bytes': PIN_BOUNDS['priv_validator_key.json']},
    ]
    service = {
        'schema': 1, 'mode': 'production-native', 'home': HOME, 'lock_directory': LOCK,
        'consensus_config': pin(f'{etc}/application-config.json', chain['application-config.json'],
                                PIN_BOUNDS['consensus_config']),
        'application_genesis': pin(f'{etc}/native-genesis.json', chain['native-genesis.json'],
                                   PIN_BOUNDS['application_genesis']),
        'root_config': pin(f'{etc}/root-config.json', small['root-config.json'], PIN_BOUNDS['small_config']),
        'root_public_inputs': [
            pin(f'{etc}/root-policy.json', chain['root-policy.json'], PIN_BOUNDS['root_policy']),
            pin(f'{etc}/root-signatures.json', chain['root-signatures.json'], PIN_BOUNDS['root_signatures']),
        ],
        'emergency_verifier_config': pin(f'{etc}/emergency-verifier.json', small['emergency-verifier.json'],
                                         PIN_BOUNDS['small_config']),
        'candidate_config': pin(f'{etc}/candidate.json', small['candidate.json'], PIN_BOUNDS['small_config']),
        'process_admission': pin(f'{etc}/admission.json', admission_raw, PIN_BOUNDS['admission']),
        'observation_pause': {'total_millis': service_value(approved, 'observation_pause.total_millis'),
                              'cleanup_reserve_millis': service_value(approved, 'observation_pause.cleanup_reserve_millis')},
        'engine_inputs': engine_inputs,
        'validator_public_key_sha256': sha256(validator_public),
        'process': {name: service_value(approved, 'process.' + name) for name in (
            'startup_millis', 'stop_millis', 'kill_millis', 'poll_millis', 'max_argument_bytes',
            'max_environment_bytes', 'max_probe_request_bytes', 'max_probe_response_bytes')},
        'environment': {},
        'monitor_interval_millis': service_value(approved, 'monitor_interval_millis'),
        'max_state_entries': service_value(approved, 'max_state_entries'),
        'metrics': {'directory': METRICS, 'interval_seconds': service_value(approved, 'metrics.interval_seconds')},
        # The sentry is the archive and serves state sync joins (D12-Q01).
        'block_history': 'archive' if role == 'sentry' else service_value(approved, 'block_history'),
        'role': role,
        'binding': pin(f'{etc}/binding.json', binding, PIN_BOUNDS['binding']),
        'catch_up_millis': service_value(approved, 'catch_up_millis'),
    }
    if role == 'sentry':
        service['snapshots'] = {'directory': SNAPSHOTS,
                                'interval_blocks': service_value(approved, 'snapshots.interval_blocks'),
                                'keep': service_value(approved, 'snapshots.keep')}
    if plan_host.get('state_sync') is not None:
        service['state_sync'] = {'light_blocks': [LIGHT_BLOCKS]}
    if role == 'endpoint':
        service['adapter_listen'] = ADAPTER_LISTEN
        service['adapter_channel'] = {'listen': plan_host['channel'],
                                      'pin': pin(f'{etc}/channel-pin.json', etc_files['channel-pin.json'],
                                                 PIN_BOUNDS['channel_pin'])}
        if plan_host.get('status'):
            service['adapter_status_listen'] = plan_host['status']
    service_raw = pretty(service)
    etc_files['service.json'] = service_raw
    for name, raw in etc_files.items():
        add(f'{etc}/{name}', raw)

    # The unit, the role profiles and the firewall table.
    exec_start = f'{bin_dir}/{roles["service_supervisor"]} --service-config {etc}/service.json'
    unit = unit_file(unit_properties['properties'], exec_start)
    add(f'/etc/systemd/system/{UNIT}.service', unit)
    # apparmor.service loads the files directly in /etc/apparmor.d at boot.
    add(f'/etc/apparmor.d/{UNIT}', policy['apparmor.profile'])
    add('/etc/nftables.d/dytallix.nft', policy['base-host-firewall.nft'])
    add(JOURNALD, JOURNALD_CONF)

    rows = []
    for path, raw in sorted(files.items()):
        under_home = path.startswith(HOME + '/')
        rows.append({'path': path, 'sha256': sha256(raw), 'bytes': len(raw),
                     'owner': USER if under_home else 'root', 'mode': '0400' if under_home else '0444'})
    directories = [
        {'path': '/opt/dytallix', 'owner': 'root', 'mode': '0755'},
        {'path': f'/opt/dytallix/{release_id}', 'owner': 'root', 'mode': '0755'},
        {'path': bin_dir, 'owner': 'root', 'mode': '0555'},
        {'path': '/etc/dytallix', 'owner': 'root', 'mode': '0755'},
        {'path': etc, 'owner': 'root', 'mode': '0755'},
        {'path': '/var/lib/dytallix', 'owner': 'root', 'mode': '0755'},
        *[{'path': p, 'owner': USER, 'mode': '0700'} for p in
          (HOME, f'{HOME}/config', f'{HOME}/data', f'{HOME}/data/cs.wal', f'{HOME}/abci', f'{HOME}/appdb', LOCK, SCRATCH)],
        {'path': METRICS, 'owner': USER, 'mode': '0755'},
        {'path': LIGHT_BLOCKS, 'owner': 'root', 'mode': '0755'},
    ] + ([{'path': SNAPSHOTS, 'owner': USER, 'mode': '0700'}] if role == 'sentry' else [])
    manifest = {
        'schema': SCHEMA, 'label': label, 'role': role, 'chain_id': catalog['chain_id'],
        'release': release_id, 'unit': UNIT,
        'account': {'user': USER, 'group': USER, 'uid': UID, 'gid': GID},
        'directories': directories,
        'binaries': [{'name': m, 'path': f'{bin_dir}/{m}', 'sha256': record_members[m]['sha256'], 'immutable': True}
                     for m in sorted(record_members)],
        'files': rows,
        'secrets': [{'path': f'{HOME}/{relative}', 'sha256': digest, 'owner': USER, 'mode': '0600'}
                    for relative, digest in sorted(secrets.items())],
        'apparmor_profiles': unit_properties['required_enforce_profiles'],
        'firewall_table': 'inet dytallix_node',
    }
    return files, manifest


def generate(release_dir, chain_dir, hosts_dir, plan, keys_dir, values, setup):
    require(setup.get('schema') == SETUP_SCHEMA and setup.get('status') == 'APPROVED', 'the setup values must be approved')
    approved = e05_approved(values)
    release = {'manifest': (Path(release_dir) / 'RELEASE_MANIFEST.json').read_bytes(),
               'record': read_json(Path(release_dir) / 'BUILD_RECORD.json')}
    chain = {name: (Path(chain_dir) / name).read_bytes() for name in
             ('application-config.json', 'native-genesis.json', 'genesis.json', 'root-policy.json', 'root-signatures.json')}
    hosts = {'dir': Path(hosts_dir), 'bindings': read_json(Path(hosts_dir) / 'PIN_PLAN_BINDINGS.json')}
    keys = {'pins': {}}
    for plan_host in plan['hosts']:
        label = plan_host['label']
        keys[label] = read_json(Path(keys_dir) / f'{label}.keys.json')
        if plan_host['role'] == 'endpoint':
            keys['pins'][label] = (Path(keys_dir) / f'{label}.channel-pin.json').read_bytes()
    out = {}
    for plan_host in plan['hosts']:
        out[plan_host['label']] = host(plan_host['label'], plan_host, release=release, chain=chain, hosts=hosts,
                                       keys=keys, approved=approved, setup=setup)
    return out


def write(out_dir, generated):
    out_dir = Path(out_dir)
    require(not out_dir.exists(), f'{out_dir} must not exist')
    for label, (files, manifest) in generated.items():
        root = out_dir / label
        for path, raw in files.items():
            target = root / PurePosixPath(path).relative_to('/')
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(raw)
        (root / 'INSTALL_MANIFEST.json').write_bytes(pretty(manifest))


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    for name in ('release', 'chain', 'hosts', 'keys', 'out'):
        parser.add_argument('--' + name, type=Path, required=True)
    parser.add_argument('--plan', type=Path, required=True)
    parser.add_argument('--values', type=Path, default=HERE.parents[2] / 'launch' / 'E05_VALUES.json')
    parser.add_argument('--setup', type=Path, default=HERE.parents[2] / 'launch' / 'hosts' / 'SETUP_VALUES.json')
    args = parser.parse_args()
    try:
        generated = generate(args.release, args.chain, args.hosts, read_json(args.plan), args.keys,
                             read_json(args.values), read_json(args.setup))
        write(args.out, generated)
    except (Invalid, OSError, KeyError) as error:
        print(f'host_files: {error}', file=sys.stderr)
        return 2
    print(json.dumps({'status': 'GENERATED', 'hosts': {label: {'files': len(files) + 1, 'release': manifest['release']}
                                                     for label, (files, manifest) in generated.items()}}, indent=2))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
