apiVersion: v1
kind: Namespace
metadata:
  name: dytallix
  labels:
    environment: testnet
    project: dytallix-bridge
    security.dytallix.io/security-level: "high"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dytallix-bridge-node
  namespace: dytallix
  labels:
    app: dytallix-bridge
    component: node
    environment: testnet
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: dytallix-bridge
      component: node
      environment: testnet
  template:
    metadata:
      labels:
        app: dytallix-bridge
        component: node
        environment: testnet
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: dytallix-bridge-sa
      automountServiceAccountToken: true
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups: [1000]
      containers:
      - name: dytallix-bridge
        image: gcr.io/PROJECT_ID/dytallix-bridge:latest
        imagePullPolicy: Always
        # Container-level security context
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 3030
          name: api
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        - containerPort: 30303
          name: p2p
          protocol: TCP
        env:
        - name: DYTALLIX_ENVIRONMENT
          value: "testnet"
        - name: DYTALLIX_LOG_LEVEL
          value: "info"
        - name: DYTALLIX_REQUIRE_TLS
          value: "true"
        - name: DYTALLIX_AUDIT_LOGGING
          value: "true"
        - name: DYTALLIX_METRICS_ENABLED
          value: "true"
        - name: DYTALLIX_CLOUD_PROVIDER
          value: "gcp"
        - name: DYTALLIX_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DYTALLIX_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: dytallix-bridge-secrets
              key: database-url
        - name: ETHEREUM_RPC_URL
          valueFrom:
            secretKeyRef:
              name: dytallix-bridge-secrets
              key: ethereum-rpc-url
        - name: COSMOS_RPC_URL
          valueFrom:
            secretKeyRef:
              name: dytallix-bridge-secrets
              key: cosmos-rpc-url
        volumeMounts:
        - name: pqc-keys
          mountPath: /etc/dytallix/keys
          readOnly: true
        - name: bridge-config
          mountPath: /etc/dytallix/config
          readOnly: true
        - name: data-volume
          mountPath: /var/lib/dytallix
        - name: logs-volume
          mountPath: /var/log/dytallix
        - name: tmp-volume
          mountPath: /tmp
        - name: var-run-volume
          mountPath: /var/run
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 4000m
            memory: 8Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
      volumes:
      - name: pqc-keys
        secret:
          secretName: dytallix-pqc-keys
          defaultMode: 0400
      - name: bridge-config
        configMap:
          name: dytallix-bridge-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: dytallix-bridge-data
      - name: logs-volume
        persistentVolumeClaim:
          claimName: dytallix-bridge-logs
      # Writable volumes for read-only root filesystem
      - name: tmp-volume
        emptyDir:
          sizeLimit: 1Gi
      - name: var-run-volume
        emptyDir:
          sizeLimit: 100Mi
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "dytallix.io/bridge-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: dytallix-bridge-service
  namespace: dytallix
  labels:
    app: dytallix-bridge
    component: service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    service.beta.kubernetes.io/gce-internal-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerClass: gce
  selector:
    app: dytallix-bridge
    component: node
    environment: testnet
  ports:
  - name: api
    port: 3030
    targetPort: 3030
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: health
    port: 8081
    targetPort: 8081
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: dytallix-bridge-p2p
  namespace: dytallix
  labels:
    app: dytallix-bridge
    component: p2p
spec:
  type: NodePort
  selector:
    app: dytallix-bridge
    component: node
    environment: testnet
  ports:
  - name: p2p
    port: 30303
    targetPort: 30303
    protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dytallix-bridge-config
  namespace: dytallix
data:
  bridge.toml: |
    [bridge]
    name = "dytallix"
    environment = "testnet"

    [ethereum]
    chain_id = 11155111  # Sepolia testnet
    confirmation_blocks = 12
    gas_limit = 500000

    [cosmos]
    chain_id = "cosmoshub-4"
    gas_limit = 200000

    [polkadot]
    chain_id = "westend"

    [security]
    pqc_enabled = true
    audit_logging = true
    require_tls = true

    [monitoring]
    metrics_enabled = true
    health_check_interval = 30

  logging.yaml: |
    level: info
    format: json
    output: stdout

    loggers:
      bridge: info
      ethereum: debug
      cosmos: debug
      polkadot: info
      pqc: info
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dytallix-bridge-data
  namespace: dytallix
  labels:
    app: dytallix-bridge
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dytallix-bridge-logs
  namespace: dytallix
  labels:
    app: dytallix-bridge
    component: logs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dytallix-bridge-sa
  namespace: dytallix
  annotations:
    iam.gke.io/gcp-service-account: dytallix-bridge-sa@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dytallix-bridge-network-policy
  namespace: dytallix
spec:
  podSelector:
    matchLabels:
      app: dytallix-bridge
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 9090
  - from: []
    ports:
    - protocol: TCP
      port: 3030
    - protocol: TCP
      port: 8081
  egress:
  - {} # Allow all egress traffic for external blockchain connections
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dytallix-bridge-hpa
  namespace: dytallix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dytallix-bridge-node
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
