# Dytallix Bridge Service Accounts
# Service accounts for each component following principle of least privilege
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dytallix-bridge-sa
  namespace: dytallix
  labels:
    app: dytallix-bridge
    component: bridge-node
    security.dytallix.io/rbac-managed: "true"
  annotations:
    # Workload Identity binding for GCP
    iam.gke.io/gcp-service-account: dytallix-bridge-sa@PROJECT_ID.iam.gserviceaccount.com
    security.dytallix.io/description: "Service account for bridge node operations"
    security.dytallix.io/permissions: "minimal-bridge-operations"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dytallix-monitoring-sa
  namespace: dytallix
  labels:
    app: dytallix-monitoring
    component: monitoring
    security.dytallix.io/rbac-managed: "true"
  annotations:
    # Workload Identity binding for GCP
    iam.gke.io/gcp-service-account: dytallix-monitoring-sa@PROJECT_ID.iam.gserviceaccount.com
    security.dytallix.io/description: "Service account for monitoring (Prometheus/Grafana)"
    security.dytallix.io/permissions: "read-only-monitoring"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dytallix-gateway-sa
  namespace: dytallix
  labels:
    app: dytallix-gateway
    component: api-gateway
    security.dytallix.io/rbac-managed: "true"
  annotations:
    # Workload Identity binding for GCP
    iam.gke.io/gcp-service-account: dytallix-gateway-sa@PROJECT_ID.iam.gserviceaccount.com
    security.dytallix.io/description: "Service account for API gateway"
    security.dytallix.io/permissions: "gateway-service-discovery"
automountServiceAccountToken: true
---
# Monitoring namespace service account for cross-namespace monitoring
apiVersion: v1
kind: Namespace
metadata:
  name: dytallix-monitoring
  labels:
    name: dytallix-monitoring
    environment: testnet
    security.dytallix.io/network-isolation: "monitoring"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: dytallix-monitoring
  labels:
    app: prometheus
    component: metrics-collector
    security.dytallix.io/rbac-managed: "true"
  annotations:
    iam.gke.io/gcp-service-account: dytallix-prometheus-sa@PROJECT_ID.iam.gserviceaccount.com
    security.dytallix.io/description: "Service account for Prometheus collection"
    security.dytallix.io/permissions: "cluster-metrics-read"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: dytallix-monitoring
  labels:
    app: grafana
    component: dashboard
    security.dytallix.io/rbac-managed: "true"
  annotations:
    iam.gke.io/gcp-service-account: dytallix-grafana-sa@PROJECT_ID.iam.gserviceaccount.com
    security.dytallix.io/description: "Service account for Grafana dashboard"
    security.dytallix.io/permissions: "read-only-metrics"
automountServiceAccountToken: false  # Grafana doesn't need K8s API access
